services:
  noticeboard:
    build: .
    image: noticeboard:latest
    container_name: noticeboard_container
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - plankstore:/opt/
    ports:
      - "5042:5042"
    environment:
      - MYRADIO_API_KEY=${MYRADIO_API_KEY}
volumes:
  plankstore:
